services:
  - type: web
    name: chess-online
    runtime: docker
    dockerfilePath: ./web/Dockerfile
    dockerContext: ./web
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: chess-db
          property: connectionString

databases:
  - name: chess-db
    plan: free
